[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.12"
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = [
  "ccxt",
  "ccxt.async_support",
  "celery",
  "celery.schedules",
  "celery.signals",
  "cloud_api",
  "cloud_api.*",
  "jose",
]
ignore_missing_imports = true
